# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Release artifactbundle

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: swiftty/swiftpm-artifactbundle-builder@v1
      with:
        swift-version: '5.7'
        depth: 1

  draft:
    needs: [ build ]

    runs-on: ubuntu-latest

    steps:
    - uses: swiftty/swiftpm-artifactbundle-bundler@v3
      id: bundler
      with:
        variants-version: ${{ github.ref_name  }}
    - uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        body: | 
          ## Checksums
          - for `.binaryTarget(name:url:checksum:)`

            ```
            ${{ steps.bundler.outputs.checksums }}
            ```

          ---
        files: |
          ${{ steps.bundler.outputs.path }}/**
